@startuml
!include ../../common/C4_Context.puml
!include ../../common/C4_Container.puml
!include ../../common/tags.puml

title System Context

Person(user, "User", "user")

System(core_system, "Core system", "Control and monitoring system")

System_Ext(llm, "LLM", "LLM")
System_Ext(notifications, "notification service", "telegram/emails")

Rel(user, core_system, "Usecase", "System configuration")
Rel_L(core_system, llm, "Usecase", "Read/Write data", $tags="external")
Rel_R(core_system, notifications,"Usecase", "Read/Write data", $tags="external")

SHOW_LEGEND()
@enduml
