RABBIT_URI_PARAM = "RABBITMQ_CONNECTION_URI"
RABBIT_QUEUE = "RABBIT_QUEUE"
RABBIT_HOST = "RABBIT_HOST"
RABBIT_PORT = "RABBIT_PORT"
RABBIT_USER = "RABBIT_USER"
RABBIT_PASSWORD = "RABBIT_PASSWORD"

BACKEND_HOST = "BACKEND_HOST"
DATA_ROOT_PATH = "DATA_ROOT_PATH"
