global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'llm-guardapi'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'llm-guardapi:8082' ]

