RABBIT_URI_PARAM = "RABBITMQ_CONNECTION_URI"
RABBIT_QUEUE = "RABBIT_QUEUE"
RABBIT_HOST = "RABBIT_HOST"
RABBIT_PORT = "RABBIT_PORT"
RABBIT_USER = "RABBIT_USER"
RABBIT_PASSWORD = "RABBIT_PASSWORD"

GPT_ADAPTER_QUEUE = "GPT_ADAPTER_QUEUE"

BACKEND_HOST = "BACKEND_HOST"
DATA_ROOT_PATH = "DATA_ROOT_PATH"

PROMETHEUS_ENDPOINT = "PROMETHEUS_ENDPOINT"
GRAFANA_ENDPOINT = "GRAFANA_ENDPOINT"
LLM_ADAPTER_ENDPOINT = "LLM_ADAPTER_ENDPOINT"
GRAFANA_SERVICE_TOKEN = "GRAFANA_SERVICE_TOKEN"
GRAFANA_FOLDER_UID = "GRAFANA_FOLDER_UID"
TELEGRAM_BOT_TOKEN = "TELEGRAM_BOT_TOKEN"
