version: "3"

services:

  web-proxy:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  app:
    build: ./guard/app/
    env_file:
      - ./guard/app/.env
    volumes:
      - ./guard/app:/app
      - ./guard/api:/api
    environment:
      - PYTHONPATH=/app:/api:/app/app/
      - COOKIE_NAME=cookie_name
    #      - CONNECTION_URI=postgresql+psycopg2://admin:postgres@database:5432/productdb
    #      - SECRET_KEY=123123
    #      - GRAFANA_ENDPOINT=http://grafana:3000
    #     - RABBIT_HOST=rabbitmq
    #      - RABBIT_PORT=5672
    #      - RABBIT_USER=admin
    #      - RABBIT_QUEUE=message
    #      - BACKEND_HOST=http://app:8081
    #      - DATA_ROOT_PATH=/data
    #      - PROMETHEUS_ENDPOINT=http://prometheus:9090
    command: python app.py
    depends_on:
      rabbitmq:
        condition: service_started
      database:
        condition: service_started
    restart: on-failure

  llm-guardapi:
    build: ./guard/guardapi/
    hostname: llm-guardapi
    volumes:
      - ./guard:/app
      - ./guard/api:/api
      - ./guard/source/models:/models/
      - ./guard/source/hg:/root/.cache/huggingface/
    command: python guardapi/app.py
    env_file:
      - ./guard/guardapi/.env
    environment:
      - PYTHONPATH=/app:/api:/app/guardapi/
    #      - CONNECTION_URI="postgresql+psycopg2://admin:postgres@database:5432/productdb"
    #      - SECRET_KEY=123123
    #     - RABBIT_HOST=rabbitmq
    #     - RABBIT_PORT=5672
    #      - RABBIT_USER=admin
    #     - RABBIT_PASSWORD=admin
    #     - RABBIT_QUEUE=message
    #     - GPT_ADAPTER_QUEUE=yandex-gpt-adapter-queue
    #      - LLM_ADAPTER_ENDPOINT=http://llm-gpt-adapter:8081
    #      - BACKEND_HOST="http://web-proxy:80"
    depends_on:
      rabbitmq:
        condition: service_started
    restart: on-failure

  llm-guard-default-filter:
    build: ./guard/guardapi/
    volumes:
      - ./guard:/app
      - ./guard/api:/api
      - ./guard/source/models:/models/
      - ./guard/source/hg:/root/.cache/huggingface/
    command: python guardapi/core/queue/rmworkers.py
    env_file:
      - ./guard/guardapi/.env
    environment:
      - PYTHONPATH=/app:/api:/app/guardapi/
    #      - RABBIT_HOST=rabbitmq
    #      - CONNECTION_URI="postgresql+psycopg2://admin:postgres@database:5432/productdb"
    #      - SECRET_KEY=123123
    #      - RABBIT_PORT=5672
    #      - RABBIT_USER=admin
    #      - RABBIT_QUEUE=message
    #      - RABBIT_PASSWORD=admin
    #      - LLM_ADAPTER_ENDPOINT=http://llm-gpt-adapter:8081
    depends_on:
      rabbitmq:
        condition: service_started
      database:
        condition: service_started
    restart: on-failure

  llm-yandex-gpt-api-adapter:
    build: ./guard/gptadapter/
    hostname: llm-gpt-adapter
    volumes:
      - ./guard:/app
      - ./guard/api:/api
    command: python gptadapter/app.py
    env_file:
      - ./guard/gptadapter/.env
    environment:
      - PYTHONPATH=/app:/api:/app/gptadapter/
      - "YANDEX_GPT_PRIVATE_KEY=${YANDEX_GPT_PEM_PRIVATE_KEY}"
      - GPT_ADAPTER_QUEUE=${GPT_ADAPTER_QUEUE}
      - YANDEX_GPT_MODEL_TYPE=yandexgpt
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - CONNECTION_URI=${CONNECTION_URI}
      - SECRET_KEY=${SECRET_KEY}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - RABBIT_QUEUE=${RABBIT_QUEUE}
      - LLM_ADAPTER_ENDPOINT=${LLM_ADAPTER_ENDPOINT}
      - YANDEX_GPT_CATALOG_ID=${YANDEX_GPT_CATALOG_ID}
      - YANDEX_GPT_SERVICE_ACCOUNT_ID=${YANDEX_GPT_SERVICE_ACCOUNT_ID}
      - YANDEX_GPT_SERVICE_ACCOUNT_KEY_ID=${YANDEX_GPT_SERVICE_ACCOUNT_KEY_ID}
      - YANDEX_GPT_IAM_URL=${YANDEX_GPT_IAM_URL}
    depends_on:
      rabbitmq:
        condition: service_started
    restart: on-failure

  webui:
    build: ./guard/app/
    env_file:
      - ./guard/app/.env
    environment:
      - PYTHONPATH=/api:/app:/app/api:/app/app/
    #      - BACKEND_HOST=http://web-proxy:80
    #      - PROMETHEUS_ENDPOINT=http://prometheus:9090
    #      - SECRET_KEY=123123
    volumes:
      - ./guard/:/app
    command: streamlit run app/home.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      app:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    restart: on-failure
    environment:
      #      - RABBITMQ_DEFAULT_USER=admin
      #      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  database:
    image: postgres:13.3
    hostname: database
    env_file:
      - ./guard/common/.env
    environment:
      #      POSTGRES_DB: productdb
      #      POSTGRES_USER: admin
      #      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  prometheus_data: { }
  grafana_data: { }
